<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="2" passed="1" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2025-03-01T16:00:06 IST" name="Default suite" finished-at="2025-03-01T16:00:19 IST" duration-ms="12881">
    <groups>
    </groups>
    <test started-at="2025-03-01T16:00:06 IST" name="Default test" finished-at="2025-03-01T16:00:19 IST" duration-ms="12881">
      <class name="TestNG.Assertions$Assertions1">
        <test-method signature="asser()[pri:0, instance:TestNG.Assertions$Assertions1@14cd1699]" started-at="2025-03-01T16:00:14 IST" name="asser" finished-at="2025-03-01T16:00:19 IST" duration-ms="4677" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Title is mismatched expected [Cognine-AI Powered Solutions] but found [Cognine - AI Powered Solutions]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Title is mismatched expected [Cognine-AI Powered Solutions] but found [Cognine - AI Powered Solutions]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at TestNG.Assertions$Assertions1.asser(Assertions.java:28)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- asser -->
      </class> <!-- TestNG.Assertions$Assertions1 -->
      <class name="TestNG.Assertions">
        <test-method signature="asser()[pri:0, instance:TestNG.Assertions@47eaca72]" started-at="2025-03-01T16:00:06 IST" name="asser" finished-at="2025-03-01T16:00:14 IST" duration-ms="8140" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- asser -->
      </class> <!-- TestNG.Assertions -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
